### ISSUE TITLE
Is this mod going to be updated to 1.7/1.8?

### ISSUE THREAD

**Issue by gizmocodes** [Dayanto/Panorama-Kit#5]
I was just wondering, because this mod is very useful. It would be so even more if it was updated to 1.7/1.8!

**Comment by Dayanto** [comment]
Roughly 2 years ago, I ended up putting the project on hold because of college and other projects taking up my time. At this point, I'm not quite sure if I'm going to end up picking it up again, and if I do, I can't give any time frames. I have a couple of things that I would love to do, such as Google Street View panorama generation, and perhaps bringing back animation, but unfortunately, one of the reasons I ended up putting it on hold was that I had built up quite a backlog of things I needed to fix and ended up falling behind with the updates, and at this point, it would probably take quite a bit of work to bring it back to life. Can't say I won't, but I can't say that I will either. I'll have to think about it.

**Comment by GizmoCodes** [comment]
Theres a new API on the rise called Nova. Its designed to be one API for all, literally. It (so far) can have mods work on both Minecraft AND Tesseralogy (I think I butchered that name). But its for 3D voxel games, so my idea is porting Panorama Kit to Nova, and allowing 3D voxel games to work for all, not just Minecraft; then anyone can make a panorama of any game. I'll mess around with Nova some more, and see what I can do.

**Comment by Dayanto** [comment]
PanoramaKit requires some rather specific things that you're unlikely to find in an API. Some even require rewriting native code due to lack of support in Forge. I had a look at the documentation, and from what I can tell, Nova is a fairly generic API and seems to lack support for even the most basic things that the mod would require, such as rotating the camera, so I don't think porting the mod to Nova would be technically possible.

**Comment by Dayanto** [comment]
I ended up removing a previous comment which turned out to be incorrect.

I had a look at the documentation for Nova, and it seems to cover much of the things required, however, I have yet to find a way that allows me to actually retrieve rendered images, which is critical for porting the mod to Nova. From the looks of it, this functionality has been abstracted away, which would make porting impossible until that gets added to the API.

If you end up finding anything while messing around with Nova, send me a message, and I'll see what I can do, but for now, Forge seems like the way to go.

**Comment by GizmoCodes** [comment]
Alright; not saying I can do much however, since I don't know too much on Java. But unfortunately, it seems the main developer of Nova, Calclavia, is having trouble developing it due to his university studies, and other developers not being interested. Currently I'm messing with trying to port it to Forge 1.7, but not sure if I'll succeed. I need to re-rent my Java book :P.
